### ISSUE TITLE
Remove JQuery dependency

### ISSUE THREAD

**Issue by ghost** [mrvautin/moostaka#4]
So I have been looking at using Moostaka for a project, a project that is in part motivated by the existing solution being a complex nightmare of dependencies that are impossible to maintain. What is appealing to me about Moostaka is that it is simple. However it could be even simpler. I have found that JQuery is largely unnecessary today. I have done a partial rewrite, good enough for me, I don't need markdown rendering so that is untested and probably not working but I am willing to share what I have if there is interest.

**Comment by mrvautin** [comment]
I agree. Very well done and merged into master.
